name: "Dependabot Pull Request"

on: "pull_request_target"

permissions:
  pull-requests: "write"
  contents: "write"

jobs:
  dependabot:
    name: "Dependabot pull request"
    runs-on: "ubuntu-latest"
    if: "${{ github.actor == 'dependabot[bot]' }}"
    steps:
      - name: "Fetch Dependabot metadata"
        id: "metadata"
        uses: "dependabot/fetch-metadata@v2.4.0"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Enable auto-merge for Dependabot pull requests"
        if: "${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch' }}"
        run: "gh pr merge --auto --squash \"${PR_URL}\""
        env:
          PR_URL: "${{ github.event.pull_request.html_url }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
